import datetime
time = datetime.datetime.now()
print(time)

print(time.year)
print(time.strftime("%A"))

time = datetime.datetime(2023, 4, 3)
print(time)
time = datetime.datetime.now()
print(time.strftime("%B"))
print(time.strftime("%a"))
print(time.strftime("%A"))
print(time.strftime("W"))
print(time.strftime("%d"))
print(time.strftime("%b"))
print(time.strftime("%B"))
print(time.strftime("%m"))
print(time.strftime("%y"))
print(time.strftime("%Y"))
print(time.strftime("%H"))
print(time.strftime("%I"))
print(time.strftime("%p"))
print(time.strftime("%M"))
print(time.strftime("%S"))
print(time.strftime("%f"))
print(time.strftime("%z"))
print(time.strftime("%Z"))
print(time.strftime("%j"))
print(time.strftime("%U"))
print(time.strftime("%W"))
print(time.strftime("%c"))
print(time.strftime("%C"))
print(time.strftime("%x"))
print(time.strftime("%X"))
print(time.strftime("%%"))
print(time.strftime("%G"))
print(time.strftime("%u"))
print(time.strftime("%V"))
